### ISSUE TITLE
Error appeared after installing submod

### ISSUE THREAD

**Issue by sparkychu** [multimokia/MAS-Submod-Auto-Atmos-Change#13]
I have no idea what the problem is, I literally just followed the installation instructions and moved the game/ folder into my DDLC folder and this error (which I have screenshotted) popped up when I tried reopening MAS. Please help me asap because I don't want to be not allowed to open MAS for a long time just because of this dumb error. 
<img width="786" alt="Capture" src="https://user-images.githubusercontent.com/87171427/125041688-e2605600-e04d-11eb-9713-4c255bf05e77.PNG">

**Comment by sparkychu** [comment]
I fixed the issue after talking to Multi, I just installed the submods incorrectly and needed to rearrange some files and delete some duplicate folders

**Comment by misstatertot** [comment]
> I fixed the issue after talking to Multi, I just installed the submods incorrectly and needed to rearrange some files and delete some duplicate folders

how did you fix it? :(
