### ISSUE TITLE
How to add submod after change of open weather map system.

### ISSUE THREAD

**Issue by At1619** [multimokia/MAS-Submod-Auto-Atmos-Change#18]
Hi, can you please help me by telling me the steps to add the submod after the generation of the API key changed from the site. I tried adding it, but in the submods menu in MAS it says that I need a valid API to use the submod, but I already made a file named 
apikey.txt and pasted the API code in there. But nothing seems to be working. Can you please help me add the submod.

**Comment by multimokia** [comment]
Unfortunately, I believe that means no new connections can be made as the API is now depreciated as is in Python2 (the version of Python used in Ren'Py), I think that means this submod is kinda out of service for new users then...

**Comment by WHATTHEDAN11** [comment]
soooo basically it doesn't work anymore?

**Comment by At1619** [comment]
It works for me perfectly fine now. Just had to enable view file extensions and saw that there was an extra .txt on the file, removed it and also made a new API key and it worked. Thanks for your help
