### ISSUE TITLE
Is this submod out of service?

### ISSUE THREAD

**Issue by WHATTHEDAN11** [multimokia/MAS-Submod-Auto-Atmos-Change#19]
Just like the title,  I dont think the API key works any more with the submod... It either shows error or other weird stuff.. I just want to know if the submod is truly out of service currently, if not then can anyone break down the steps one by one in a rly detailed way?

**Comment by At1619** [comment]
The submod is working for me now, for the API coded make a new account and click on your profile and click on my API keys and generate one there. And when you make the file make a text file and name it apikey, dont add the .txt because it should automatically add it by itself. Also make sure you have view file extensions on, which you can turn on by clicking view and selecting it. Doing it like that it worked for me and should work for you as well.

**Comment by WHATTHEDAN11** [comment]
for the key, do we just paste it in the apikey text file?

**Comment by At1619** [comment]
yes

**Comment by WHATTHEDAN11** [comment]
Ok, i just did everything u said, but My Monika still haven't asked about anything yet, does it take some time for her to notice?

**Comment by At1619** [comment]
open settings and go to submods and stay there fir like a minute and go back, thats what I did, and she then asked me about my location

**Comment by WHATTHEDAN11** [comment]
It says 'api key valid' when i check the 'submod setting', im guessin i just hav to wait for her to ask me then

**Comment by At1619** [comment]
yeah

**Comment by WHATTHEDAN11** [comment]
bruh she still havent asked me anything

**Comment by WHATTHEDAN11** [comment]
bro, she just asked me, and when I told her she said 'wow it looks like you live in the only 'city name' in the world! Or at least from what i know' and then it says an exceptional error occured....
heres the log: 
[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-ch30.rpy", line 1492, in script call
  File "game/event-handler.rpy", line 2532, in script call
  File "game/Submods/Auto Weather Change/awc_topics.rpy", line 81, in script
    $ awc_savePlayerCityCountryTup((temp_city, awc_getCityCountry(temp_city)))
  File "game/Submods/Auto Weather Change/awc_topics.rpy", line 81, in <module>
    $ awc_savePlayerCityCountryTup((temp_city, awc_getCityCountry(temp_city)))
  File "game/Submods/Auto Weather Change/Utilities/awc_utils.rpy", line 252, in awc_getCityCountry
    return store.awc_globals.owm.weather_at_place(city_name).get_location().get_country()
UnauthorizedError: Your API subscription level does not allow to perform this operationReason: Invalid API key

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-ch30.rpy", line 1492, in script call
  File "game/event-handler.rpy", line 2532, in script call
  File "game/Submods/Auto Weather Change/awc_topics.rpy", line 81, in script
    $ awc_savePlayerCityCountryTup((temp_city, awc_getCityCountry(temp_city)))
  File "C:\Users\23767\Desktop\Moncake\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\23767\Desktop\Moncake\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/Submods/Auto Weather Change/awc_topics.rpy", line 81, in <module>
    $ awc_savePlayerCityCountryTup((temp_city, awc_getCityCountry(temp_city)))
  File "game/Submods/Auto Weather Change/Utilities/awc_utils.rpy", line 252, in awc_getCityCountry
    return store.awc_globals.owm.weather_at_place(city_name).get_location().get_country()
  File "C:\Users\23767\Desktop\Moncake\game\python-packages\pyowm-2.8.0-py2.7.egg\pyowm\webapi25\owm25.py", line 231, in weather_at_place
    'lang': self._language})
  File "C:\Users\23767\Desktop\Moncake\game\python-packages\pyowm-2.8.0-

**Comment by At1619** [comment]
I dont know what to do there then, she said the same to me and then the submod started working but I didnt get any error.

**Comment by WHATTHEDAN11** [comment]
is it ok if i ask which city did u wrote in? Maybe its because the api key isnt suitable for every city

**Comment by At1619** [comment]
Did you spell the city name correctly? maybe you made a typo, i dont really know how to help you there.

**Comment by WHATTHEDAN11** [comment]
Im pretty sure theres no typo... i've even tried those big cities like New York

**Comment by WHATTHEDAN11** [comment]
oh nvm i think it worked

**Comment by WHATTHEDAN11** [comment]
wait, so this time no error occured, i wanna ask after u enabled it, can u still change weather manually?

**Comment by At1619** [comment]
yes, monika can change the weather to what you want it to be.

**Comment by WHATTHEDAN11** [comment]
then how do u know if the submod's working😂

**Comment by At1619** [comment]
because it changes automatically to what the weather in your area is.

**Comment by WHATTHEDAN11** [comment]
do u have to restart for it to change or it'll change automatically

**Comment by WHATTHEDAN11** [comment]
the game is slower than usual to load for me... Is it the same for urs?

**Comment by At1619** [comment]
it should change by itself in a bit, but you can try restarting. no mines running the same as usual

**Comment by WHATTHEDAN11** [comment]
I just realised sth, if u install dis submod u gotta make sure ur connected to the internet, it could not run without the internet

**Comment by multimokia** [comment]
Yeah this submod **requires** internet connection as the only way to get weather info is by pulling from OpenWeatherMap's API

**Comment by multimokia** [comment]
The game will also be slightly slower to load due to some initial requests needing to be made
