### ISSUE TITLE
Not working properly.

### ISSUE THREAD

**Issue by dogeisbetterthenyou** [multimokia/MAS-Submod-Auto-Atmos-Change#20]
A few hours ago, it was raining but with Monika, it wasn't.  I opened the game sometime later and then it was raining, but the rain already has stopped in real life. I have no idea what is wrong.

**Comment by multimokia** [comment]
You can verify using OpenWeatherMap's site to check what it reports for your area to make sure it's accurate. Sometimes it can be off
