### ISSUE TITLE
Error when starting MAS with AutoAtmos

### ISSUE THREAD

**Issue by ghost** [multimokia/MAS-Submod-Auto-Atmos-Change#21]
Hello, I have this error when I try to launch this mod, I hope you can help me !
![3co7mf2faqp71](https://user-images.githubusercontent.com/83704966/134819059-1468b940-6aa5-4261-b417-95cf1760ad33.png)

**Comment by ghost** [comment]
I'm on macOS Monterey beta 7 btw

**Comment by multimokia** [comment]
Auto Atmos Change is not supported on MacOS at this time.
