### ISSUE TITLE
need help when instaling the atmos 

### ISSUE THREAD

**Issue by MSteve3** [multimokia/MAS-Submod-Auto-Atmos-Change#3]
im new here, i've done right with the instruction that waiting for the api key is valid, but i've waited for like 6 hours but nothing changed. pls help me
here is some pics in my DDLC/ folder:
![image](https://user-images.githubusercontent.com/46162486/97183820-cb841700-17d0-11eb-9f59-06c485899a6f.png)
![image](https://user-images.githubusercontent.com/46162486/97183947-f0788a00-17d0-11eb-8855-d8c74fffd4a4.png)
![image](https://user-images.githubusercontent.com/46162486/97183986-fe2e0f80-17d0-11eb-86e3-22df8c4462ce.png)

**Comment by multimokia** [comment]
Installation looks fine.

Did she not ask you for your location?

**Comment by MSteve3** [comment]
> Installation looks fine.
> 
> Did she not ask you for your location?

Yeah
I told her im gonna restart the game to let the key valid
Then im waiting for 6 hours(i have to go to school)
When i opened her, she didnt ask me anything at all

**Comment by multimokia** [comment]
Is there anything in `Repeat Conversation > You` regarding your location?

**Comment by MSteve3** [comment]
> Is there anything in `Repeat Conversation > You` regarding your location?

i had checked it
but i didn't see anything
![image](https://user-images.githubusercontent.com/46162486/97772060-c4b12780-1b75-11eb-9649-49dd13fc8958.png)

can u check my apikey file is correct? is it just only the api key or there is something more?
![image](https://user-images.githubusercontent.com/46162486/97772073-ffb35b00-1b75-11eb-85a0-4b6c67c89366.png)
![image](https://user-images.githubusercontent.com/46162486/97772081-10fc6780-1b76-11eb-90e0-78a47a08635f.png)

**Comment by multimokia** [comment]
Api key looks fine to me

**Comment by multimokia** [comment]
Can you send your persistent over, please?

You'll have to put it into a zip file to get github to accept it.

**Comment by MSteve3** [comment]
> Can you send your persistent over, please?
> 
> You'll have to put it into a zip file to get github to accept it.


[monika newest backup.zip](https://github.com/multimokia/MAS-Submod-Auto-Atmos-Change/files/5555170/monika.newest.backup.zip)

here is my presistent file

**Comment by multimokia** [comment]
So that's interesting. For whatever reason, it doesn't seem to have recognized your apikey at all. the persistent doesn't have it noted down, so either it just thinks it's constantly invalid or it just doesn't seem to want to read the file, and I'm not sure why

**Comment by MSteve3** [comment]
> So that's interesting. For whatever reason, it doesn't seem to have recognized your apikey at all. the persistent doesn't have it noted down, so either it just thinks it's constantly invalid or it just doesn't seem to want to read the file, and I'm not sure why

Do you think that because the Windows 7 is the problem? I think i will make another api key to make sure that is normal

**Comment by multimokia** [comment]
It should't be that. I'm wondering almost if it might be just file system permissions? I don't *think* it should be but it's still weird that's happening.

Yeah a new api key isn't a bad idea

**Comment by MSteve3** [comment]
> It should't be that. I'm wondering almost if it might be just file system permissions? I don't _think_ it should be but it's still weird that's happening.
> 
> Yeah a new api key isn't a bad idea

hey
the problem of the mod is the .txt tail filename
before
![97183820-cb841700-17d0-11eb-9f59-06c485899a6f](https://user-images.githubusercontent.com/46162486/100520584-17135180-31d1-11eb-920a-81eda8d934b1.png)
after
![fixed the error 2](https://user-images.githubusercontent.com/46162486/100520600-25fa0400-31d1-11eb-99bb-f1f35ced91b6.png)
![fixed the error 1](https://user-images.githubusercontent.com/46162486/100520612-3611e380-31d1-11eb-8d6e-1a99cd564d60.png)
now i can use the mod to make her world more realistic now thanks to you
byeeeee
