### ISSUE TITLE
The climate isn't changing

### ISSUE THREAD

**Issue by NegativeOne404** [multimokia/MAS-Submod-Auto-Atmos-Change#4]
Well, i've been using the subod for a week, and the climate hasn't changed at all, even when it rained (a lot) here.
I generated the API at "Open Weather" and put it in a ".txt" file at the MAS folder (the one with the "DDLC.exe"); The folder "game", I've put at the MAS folder too. In the game, Monika asked my location, and efter that the climate doesn't change from "Clear".

![image](https://user-images.githubusercontent.com/55655845/98537507-235a5d80-2268-11eb-8813-e631d60924b3.png)

"DDLC-1.1.1-pc\game\Submods"
![image](https://user-images.githubusercontent.com/55655845/98536940-53553100-2267-11eb-800a-045d2db76c64.png)
![image](https://user-images.githubusercontent.com/55655845/98536985-5fd98980-2267-11eb-9552-85499051e78b.png)

**Comment by multimokia** [comment]
Asking a stupid question here, but what's the current weather in MAS set to for you? Clear or progressive?

Also, what is the weather like in your area? Is it reflected properly on https://openweathermap.org?

If not, is it just a light rain/snow/etc? The values are a little biased as the MAS weather is more for heavier levels of rain/snow/cloud cover to actually set it off, in order to seem a little more realistic

**Comment by NegativeOne404** [comment]
Seeing it right now, at MAS is clear, and at OpenWeather is "Thunderstorm".
![image](https://user-images.githubusercontent.com/55655845/98994547-c2a07e80-250e-11eb-8efc-ef8a07cdaad4.png)
![image](https://user-images.githubusercontent.com/55655845/98994217-38f0b100-250e-11eb-921a-0ad0a61ff29e.png)

**Comment by multimokia** [comment]
I mean more in terms of your option in weather. It's possible the weather might be just set to `Clear` (not Progressive, which Auto Atmos Change runs on)

If you try to select `Progressive` from the weather menu, does Monika change it? (She won't say `that's the weather right now` or anything similar)

**Comment by NegativeOne404** [comment]
Oooohhhhh, i get it now. The mod is activated at the "Progressive" weather. I didn't thought about that... Haha, sorry. And yes, Monika changed it. Thx @multimokia

**Comment by multimokia** [comment]
Haha no problem! Glad it's resolved
