### ISSUE TITLE
Verifying the API key

### ISSUE THREAD

**Issue by Strawberri39** [multimokia/MAS-Submod-Auto-Atmos-Change#6]
Does anybody know how to make your API key valid? I went to the correct website and copied the API key I generated. I then made a .txt file with the name "apikey.txt" and put in the the DDLC directory (The same folder where DDLC.exe is) and pasted the API key in it. It said to wait a few hours so I left it overnight just in case. It still says "Please add a valid API key to use this submod." Does anybody know what I am doing wrong? (Sorry for any grammatical mistakes I might have made.)

**Comment by multimokia** [comment]
Hey there, can I see a screenshot of your `DDLC` directory, please? Just want to make sure everything's 100% in order

**Comment by Strawberri39** [comment]
![Doki Doki Literature Club 1_26_2021 9_44_14 AM](https://user-images.githubusercontent.com/77985188/105860185-4f5dc300-5fbb-11eb-911d-7f3c3bb01e20.png)
Of course!

**Comment by multimokia** [comment]
Ah I see the issue, notice how the other text files in your directory don't have a `.txt` extension. Windows hides them by default, which means your `apikey.txt` file is *actually* `apikey.txt.txt`

Simply remove the `.txt` you added there and it should be fine once you start MAS

**Comment by Strawberri39** [comment]
Ohhh I see, Thank you!

**Comment by multimokia** [comment]
No problem!
